mfd: rk806-i2c: Fix compilation errors on kernel 6.1
drivers/mfd/rk806-i2c.c:56:14: error: incompatible function pointer types initializing 'void (*)(struct i2c_client *)' with an expression of type 'int (struct i2c_client *)'

Fixes: b473fca294b2 ("mfd: rk806: Add RK806 support i2c")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I00e7088be388222a914824fbc5c5e1ebef021e8a