drm/bridge: maxim-max96755: Add missing break in max96755f_link_parse
drivers/gpu/drm/bridge/maxim-max96755f.c:469:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
        case 1:
        ^

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I60ad30cc810080f0a0d62b1e805e37b1c532e9a6