input: touchscreen: elan: Add missing break in elan_iap_ioctl
drivers/input/touchscreen/elan/elan_ts.c:1471:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
        default:
        ^

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I7b8d9d1d90d2fff2308ae0f9663447af6fd91569