iio: imu: lsm6dsr: make use of devm_iio_kfifo_buffer_setup() helper
According to commit 17395ce29921 ("iio: make use of devm_iio_kfifo_buffer_setup() helper")
and commit f67c6c73cb07 ("iio: core: Simplify the registration of kfifo buffers").

Also fixes the following warning:
drivers/iio/imu/st_lsm6dsr/st_lsm6dsr_buffer.c:992:19: error: implicit declaration of function 'of_property_read_bool' [-Werror=implicit-function-declaration]

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Ia8229b4fe1d22c6455ea8b1eeb410a925f71e785